### ISSUE TITLE
特殊音素系の再提出

### ISSUE THREAD

**Issue by ramura0708** [UniPro-tech/ramura-arane-site#35]
動くことを確認したので更新
結構ファイルサイズがデカいのでドライブのリンクを付属しておきます

・特殊音素は個別でDLできるようにすること
・単体では使用できないことを記載する
・特殊音素のエイリアスは「E」であることを記載してると直よし

追記
記入時点ではドライブへのアップロードが完全に終わってないので、もし何かが欠けてるようだったら伝えてください

https://drive.google.com/drive/folders/10cM7SeFJxt_ZAD3JrAE8PbaI5lNqYKEt

**Comment by yuito-it** [comment]
@ramura0708 既存の特殊音源のIssueがあるので、そちらに統合 #34
